import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "../components/footer/Footer.jsx";
import NavBar from "../components/navBar/NavBar.jsx";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "BATCH-13-ASSIGNMENT-07",
  description: "GENERATED BY ABU RAYHAN KOBIR",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="container mx-auto min-h-full flex flex-col">
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
